# Battery
CONFIG_ADC=y

# SHT
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SHT4X=y

# Basic BT options
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="YZ"

# MCUBOOT FOTA
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y

# Yuzu settings
# CONFIG_YUZU_SAMPLE_INTERVAL_MS=20000

# Logging
CONFIG_LOG=y
# Allow room to print logs and allow for bt inititilization
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096